# Generated by Django 5.2 on 2025-04-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0002_remove_document_content_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]

# touched on 2025-07-10T16:40:16.685933Z